export const ADD_TODOITEM = 'ADD_TODOITEM';
export const ADD_TODOITEM_SUCCESS= 'ADD_TODOITEM_SUCCESS';
export const ADD_TODOITEM_FAILED= 'ADD_TODOITEM_FAILED';

export const GET_TODOITEM = 'GET_TODOITEM';
export const DELETE_TODOITEM = 'DELETE_TODOITEM';
export const MARK_AS_DONE_TODOITEM = 'MARK_AS_DONE_TODOITEM';
export const EDIT_TODOITEM = 'EDIT_TODOITEM';
export const FETCH_TODOLIST = 'FETCH_TODOLIST';
export const GET_TODOITEMS = 'GET_TODOITEMS';
export const FETCH_TodoList_START = 'FETCH_TodoList_START';
export const FETCH_TodoList_SUCCESS = 'FETCH_TodoList_SUCCESS';
export const FETCH_TodoList_FAILED = 'FETCH_TodoList_FAILED';
export const EDIT_TODOITEM_SUCCESS = 'EDIT_TODOITEM_SUCCESS';
export const EDIT_TODOITEM_FAILED = 'EDIT_TODOITEM_FAILED';

export const FINISH_TODOITEM_SUCCESS = 'FINISH_TODOITEM_SUCCESS';
export const FINISH_TODOITEM_FAILED = 'FINISH_TODOITEM_FAILED';

export const DELETE_TODOITEM_SUCCESS = 'DELETE_TODOITEM_SUCCESS';
export const DELETE_TODOITEM_FAILED = 'DELETE_TODOITEM_FAILED';

export const FETCH_SELECTED_ITEM = 'FETCH_SELECTED_ITEM';





//AUTh

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_REDIRECT_PATH = 'SET_REDIRECT_PATH';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';